name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o hellodotnetcore
    - name: 'Deploy'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: sphillips-demo # Replace with your app name
        publish-profile: $ # Define secret variable in repository settings as per action documentation
        package: './hellodotnetcore' 

